In [4]:
# ==========================================================
# 🧹 Data Cleaning – Drop Unnecessary Columns (Actual Columns)
# ==========================================================
import pandas as pd

# --- Load CSVs ---
users_df   = pd.read_csv("dataset/users.csv")
hotels_df  = pd.read_csv("dataset/hotels.csv")
reviews_df = pd.read_csv("dataset/reviews.csv")

# --- Drop unneeded columns ---
users_drop_cols   = ["join_date"]  # optional
hotels_drop_cols  = ["hotel_name", "star_rating", "lat", "lon"]
reviews_drop_cols = ["review_text"]  # only if exists

users_df.drop(columns=users_drop_cols, errors='ignore', inplace=True)
hotels_df.drop(columns=hotels_drop_cols, errors='ignore', inplace=True)
reviews_df.drop(columns=reviews_drop_cols, errors='ignore', inplace=True)

# --- Show updated shapes ---
print(f"✅ Users dataframe shape after drop  : {users_df.shape}")
print(f"✅ Hotels dataframe shape after drop : {hotels_df.shape}")
print(f"✅ Reviews dataframe shape after drop: {reviews_df.shape}")

# --- Quick preview ---
display(users_df.head())
display(hotels_df.head())
display(reviews_df.head())

✅ Users dataframe shape after drop  : (2000, 5)
✅ Hotels dataframe shape after drop : (25, 9)
✅ Reviews dataframe shape after drop: (50000, 11)

   user_id user_gender         country age_group traveller_type
0        1      Female  United Kingdom     35-44           Solo
1        2        Male  United Kingdom     25-34           Solo
2        3      Female          Mexico     25-34         Family
3        4        Male           India     35-44         Family
4        5       Other           Japan     25-34           Solo

,hotel_id,city,country,cleanliness_base,comfort_base,facilities_base,location_base,staff_base,value_for_money_base
0,1,New York,United States,9.1,8.8,8.9,9.5,8.6,8.0
1,2,London,United Kingdom,9.0,9.2,8.8,9.4,9.0,7.9
2,3,Paris,France,8.8,9.4,8.7,9.6,9.3,8.1
3,4,Tokyo,Japan,9.6,9.0,9.3,8.5,9.5,8.2
4,5,Dubai,United Arab Emirates,9.3,9.5,9.6,8.9,9.4,8.5

,review_id,user_id,hotel_id,review_date,score_overall,score_cleanliness,score_comfort,score_facilities,score_location,score_staff,score_value_for_money
0,1,1600,1,2022-10-07,8.7,8.6,8.7,8.5,9.0,8.8,8.7
1,2,432,4,2020-03-24,9.1,10.0,9.1,9.0,8.6,9.4,8.6
2,3,186,18,2023-12-18,8.8,9.7,8.8,8.3,8.7,8.1,8.6
3,4,1403,19,2022-06-22,8.9,9.0,8.8,8.5,9.6,9.1,8.3
4,5,1723,17,2022-07-02,9.1,8.9,9.5,9.3,8.3,9.4,8.9

In [16]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path("dataset")

users   = pd.read_csv(DATA_DIR / "users.csv")
hotels  = pd.read_csv(DATA_DIR / "hotels.csv")
reviews = pd.read_csv(DATA_DIR / "reviews.csv")

print("Loaded -> users:", users.shape, "| hotels:", hotels.shape, "| reviews:", reviews.shape)

# ==========================================================
# 🔗 Data Merging – Combine Users, Hotels, and Reviews
# ==========================================================

# --- Merge reviews with users on user_id ---
merged_df = pd.merge(reviews_df, users_df, on="user_id", how="left")

# --- Merge the result with hotels on hotel_id ---
merged_df = pd.merge(merged_df, hotels_df, on="hotel_id", how="left")

# --- Show shape and preview ---
print(f"✅ Final merged dataset shape: {merged_df.shape}")
display(merged_df.head())

# --- Optional sanity check ---
print("\nMissing values per column:")
print(merged_df.isnull().sum())

# --- Save merged dataset (for later use) ---
merged_df.to_csv("dataset/hotel_reviews_merged.csv", index=False)
print("\n💾 Merged dataset saved to: dataset/hotel_reviews_merged.csv")

Loaded -> users: (2000, 6) | hotels: (25, 13) | reviews: (50000, 12)
✅ Final merged dataset shape: (50000, 23)

,review_id,user_id,hotel_id,review_date,score_overall,score_cleanliness,score_comfort,score_facilities,score_location,score_staff,score_value_for_money,user_gender,country_x,age_group,traveller_type,city,country_y,cleanliness_base,comfort_base,facilities_base,location_base,staff_base,value_for_money_base
0,1,1600,1,2022-10-07,8.7,8.6,8.7,8.5,9.0,8.8,8.7,Female,New Zealand,25-34,Solo,New York,United States,9.1,8.8,8.9,9.5,8.6,8.0
1,2,432,4,2020-03-24,9.1,10.0,9.1,9.0,8.6,9.4,8.6,Female,United Kingdom,35-44,Couple,Tokyo,Japan,9.6,9.0,9.3,8.5,9.5,8.2
2,3,186,18,2023-12-18,8.8,9.7,8.8,8.3,8.7,8.1,8.6,Female,Spain,55+,Couple,Cairo,Egypt,8.8,8.7,8.6,9.1,8.7,8.4
3,4,1403,19,2022-06-22,8.9,9.0,8.8,8.5,9.6,9.1,8.3,Female,United Kingdom,35-44,Business,Barcelona,Spain,9.2,9.1,8.9,9.7,9.0,8.8
4,5,1723,17,2022-07-02,9.1,8.9,9.5,9.3,8.3,9.4,8.9,Male,Australia,45-54,Family,Moscow,Russia,9.1,9.3,9.0,9.0,9.1,8.6

Missing values per column:
review_id                0
user_id                  0
hotel_id                 0
review_date              0
score_overall            0
score_cleanliness        0
score_comfort            0
score_facilities         0
score_location           0
score_staff              0
score_value_for_money    0
user_gender              0
country_x                0
age_group                0
traveller_type           0
city                     0
country_y                0
cleanliness_base         0
comfort_base             0
facilities_base          0
location_base            0
staff_base               0
value_for_money_base     0
dtype: int64

💾 Merged dataset saved to: dataset/hotel_reviews_merged.csv